# SQLite datasource
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Ensure schema.sql is executed on startup
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Logging
logging.level.root=INFO
logging.level.org.springframework.jdbc=DEBUG
